### PR TITLE
Fixing syntax parse error.

### PR DESCRIPTION
**Pull request by renatonascalves**
The code was using php functions, <? ?>, that were causing problems in my site. Not allowing the settings page to be shown.

Here is the log of the error: [21-Mar-2017 13:10:34 UTC] PHP Parse error:  syntax error, unexpected end of file in /srv/www/opera/htdocs/wp-content/plugins/postmark-wordpress/page-settings.php on line 144

The proposed changes fixed this error and the settings page is showing again.

### CODE REVIEW

**Comment by renatonascalves** [comment]
Sorry about the tab change... My sublime text automatically changes it. :(

**Comment by atheken** [comment]
@renatonascalves, thanks for the PR. Can you try to fix the indentation back to what it was? The entire file appears to have changed, though I am thinking this is a minor change?

**Comment by renatonascalves** [comment]
Sure! I'll fix it!

**Comment by atheken** [comment]
Thanks! Just curious, what version of PHP are you running where this was creating an error?

**Comment by renatonascalves** [comment]
Btw @atheken I don't think this is so minor. Without this fix, this is how I see it: 
screenshot_1

Nginx / PHP 7.17

**Pull request merged**
