### PR TITLE
Register and recognize response headers for cc, bcc, and reply-to

### PR DESCRIPTION
**Pull request by andrewhaines**
This is derived from (pretty explicitly) Gagan Deep Singh's updates elsewhere.

### CODE REVIEW

**Comment by andrewhaines** [comment]
Found a few more (re)testing issues once initially requested.

**Comment by jptoto** [comment]
@andrewhaines Thanks for the PR!

**Comment by JamesJosephFinn** [comment]
@andrewhaines Is there a code example of the filter(s) used to set these headers? For example, currently I'm using this snippet with the Sparkpost plugin to set `replyto`:

```php
add_filter('wpsp_reply_to', function($replyTos) {
    return 'Foo Bar <foo@bar.dev>';
});
```

Many thanks! Pax!

**Comment by pgraham3** [comment]
@JamesJosephFinn Can you try something like this:

```php
add_filter( 'wp_mail', function( $headers['Reply-To'] ) {
  return 'Foo Bar <foo@bar.dev>';
});
```

The Postmark plugin overrides `wp_mail` so you can hook into it for setting the Reply-To address. If you are going to be using the same Reply-To address consistently for a sender signature, you can also set that up within the Postmark account as well.

**Pull request merged**
